### ISSUE TITLE
Subnatica Not Responding

### ISSUE THREAD

**Issue by boxingink713994** [Esper89/Subnautica-TerrainPatcher#5] opened 2022-12-06 04:16 UTC
Added the mod, subnautica stopped working

when i remove the mod it works again. when i add it it doesnt.
[qmodmanager_log-Subnautica.txt](https://github.com/Esper89/Subnautica-TerrainPatcher/files/10162207/qmodmanager_log-Subnautica.txt)
log attached

**Comment by Esper89** [comment] 2022-12-06 04:54
~~Duplicate of #4.~~

**Comment by Esper89** [comment] 2022-12-06 19:48
Nevermind, this is not a duplicate, I read that log wrong. It seems like you've installed some of your mods improperly; I'd recommend doing a full reinstall of the game, then reinstalling QMM and TerrainPatcher. If the issue persists, send your new log file with just TerrainPatcher installed.

**Comment by boxingink713994** [comment] 2022-12-06 20:46
Thank you!

**Closed as completed** 2023-01-04 01:06 UTC
Labels: bug
